name: scan_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # ML Kit
  google_mlkit_text_recognition: ^0.15.0

  # UI & Fonts
  google_fonts: ^6.2.1
  animate_do: ^4.2.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  # Image Picker
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.6
  firebase_storage: ^12.4.6
  http: ^1.4.0
  flutter_dotenv: ^5.2.1

  # Icons
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/tessdata/bul.traineddata
